### ISSUE TITLE
Bruh please

### ISSUE THREAD

**Issue by Guru322** [salmanytofficial/XLICON-V2-MD#2]
@abrahamdw882 bruh😭 change your profile pic , i can't fap 7 times to that

**Comment by abrahamdw882** [comment]
Bruh😅

**Comment by abrahamdw882** [comment]
@Guru322 🤣

**Comment by mznking** [comment]
@Guru322 _Can i contact you? I'll try to contact you in whatsapp. But, you are not replying_ 😬

**Comment by Guru322** [comment]
> @Guru322 _Can i contact you? I'll try to contact you in whatsapp. But, you are not replying_ 😬

Drop a msg on +972 52-829-1070

**Comment by mznking** [comment]
Okay Bro
